version: '3.7'

services:
  frea:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080:8080"
    environment:
      - FREA_DEBUG_MODE=false
      - POSTGRES_HOST=db
      - POSTGRES_DB=frea
      - POSTGRES_USER=frea
      - POSTGRES_PASSWD=MeaningOfLife
    links:
      - db
    #volumes:
      #- ./tmp/mecab:/app/mecab

  db:
    restart: always
    image: postgres:15
    environment:
      - POSTGRES_DB=frea
      - POSTGRES_USER=frea
      - POSTGRES_PASSWORD=MeaningOfLife
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@freasearch.org
      PGADMIN_DEFAULT_PASSWORD: frea
    links:
      - db
    logging:
      # ターミナルを汚しまくるのでログを粛清
      driver: none
