version: '3.7'

services:
  frea:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080:8080"

  db:
    container_name: db
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
