version: '3.7'

services:
  frea:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080:8080"
    environment:
      - FREA_DEBUG_MODE=false
      - POSTGRES_HOST=db
      - POSTGRES_DB=frea
      - POSTGRES_USER=frea
      - POSTGRES_PASSWD=meaning_of_life

  db:
    restart: always
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=frea
      - POSTGRES_USER=frea
      - POSTGRES_DB=meaning_of_life
    volumes:
      - ./db:/var/lib/postgresql/data
